image:
- Visual Studio 2022
- Visual Studio 2019
build: "off"
on_failure:
- ps: $blockrdp = $true; iex ((new-object net.webclient).downloadstring('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
init:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
- ps: |
    # FIXME: workaround: clear some space
    docker rmi mcr.microsoft.com/dotnet/framework/aspnet:4.8
    docker rmi mcr.microsoft.com/windows/nanoserver:1803
    docker rmi mcr.microsoft.com/windows/nanoserver:1809
    docker rmi mcr.microsoft.com/windows/nanoserver:sac2016
    docker rmi mcr.microsoft.com/windows/servercore:1803
    docker rmi mcr.microsoft.com/windows/servercore:ltsc2016
- ps: |
    docker info
    docker version
    $winver = Get-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\'
    $versiontag = "$($winver.CurrentMajorVersionNumber).$($winver.CurrentMinorVersionNumber).$($winver.CurrentBuildNumber).$($winver.UBR)"
    $versiontag
- ps: |
    &$Env:ProgramFiles\Docker\Docker\DockerCli.exe -SwitchDaemon
- ps: |
    &$Env:ProgramFiles\Docker\Docker\DockerCli.exe -SwitchWindowsEngine
install:
- ps: echo $Env:DOCKER_PASSWORD | docker login --username $Env:DOCKER_USERNAME --password-stdin
- ps: |
    [System.Environment]::OSVersion
    systeminfo.exe | sls Version
    winver
- ps: docker images
- ps: |
    docker build --tag ${Env:DOCKER_USERNAME}/paperdraw:appveyor .
- ps: |
    docker push docker.io/${Env:DOCKER_USERNAME}/paperdraw:appveyor
