image:
- Visual Studio 2022
- Visual Studio 2019
build: "off"
on_failure:
- ps: $blockrdp = $true; iex ((new-object net.webclient).downloadstring('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
init:
# FIXME: workaround: clear some space
- ps: |
    $save = "mcr.microsoft.com/windows/servercore:ltsc2019"
    $script = Join-Path . "space.ps1"
    If(Test-Path $script){ Remove-Item $script; }
    docker images  --format "{{json . }}" | ConvertFrom-json | Foreach-Object {
        $image = "$($_.Repository):$($_.TAG)"
        if (!($image.Contains($save))) {
            echo "Write-Host removing $image" | Out-File -Append -Encoding ASCII $script
            echo "`$result = docker rmi $image" | Out-File -Append -Encoding ASCII $script
        }
    }
    cat $script
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
- ps: |
    docker info
    docker version
    $winver = Get-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\'
    $versiontag = "$($winver.CurrentMajorVersionNumber).$($winver.CurrentMinorVersionNumber).$($winver.CurrentBuildNumber).$($winver.UBR)"
    $versiontag
- ps: |
    &$Env:ProgramFiles\Docker\Docker\DockerCli.exe -SwitchDaemon
- ps: |
    &$Env:ProgramFiles\Docker\Docker\DockerCli.exe -SwitchWindowsEngine
install:
- ps: |
    [System.Environment]::OSVersion
    systeminfo.exe | sls Version
    winver
- ps: docker images
- ps: echo $Env:DOCKER_PASSWORD | docker login --username $Env:DOCKER_USERNAME --password-stdin
- ps: |
    docker build --tag $Env:DOCKER_USERNAME/paperdraw:appveyor .
- ps: |
    docker push docker.io/$Env:DOCKER_USERNAME/paperdraw:appveyor
