image:
- Visual Studio 2022
- Visual Studio 2019
build: "off"
on_failure:
- ps: $blockrdp = $true; iex ((new-object net.webclient).downloadstring('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
init:
- ps: |
    # FIXME: workaround: clear some space
    $save = "mcr.microsoft.com/windows/servercore:ltsc2019"
    docker images  --format "{{json . }}" | ConvertFrom-json | Foreach-Object {
        $image = "$($_.Repository):$($_.TAG)"
        if (!($image.Contains($save))) {
            Write-Host removing $image
            docker rmi $image
        }
    }
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
- ps: |
    docker info
    docker version
    $winver = Get-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\'
    $versiontag = "$($winver.CurrentMajorVersionNumber).$($winver.CurrentMinorVersionNumber).$($winver.CurrentBuildNumber).$($winver.UBR)"
    $versiontag
- ps: |
    &$Env:ProgramFiles\Docker\Docker\DockerCli.exe -SwitchDaemon
- ps: |
    &$Env:ProgramFiles\Docker\Docker\DockerCli.exe -SwitchWindowsEngine
install:
- ps: |
    [System.Environment]::OSVersion
    systeminfo.exe | sls Version
    winver
- ps: docker images
- ps: echo $Env:DOCKER_PASSWORD | docker login --username $Env:DOCKER_USERNAME --password-stdin
- ps: |
    docker build --tag $Env:DOCKER_USERNAME/paperdraw:appveyor .
- ps: |
    docker push docker.io/$Env:DOCKER_USERNAME/paperdraw:appveyor
