image:
- Visual Studio 2022
- Visual Studio 2019
build: "off"
init:
- ps: |
    &$Env:ProgramFiles\Docker\Docker\DockerCli.exe -SwitchDaemon
- ps: |
    &$Env:ProgramFiles\Docker\Docker\DockerCli.exe -SwitchWindowsEngine
install:
- ps: |
    [System.Environment]::OSVersion.Version
    systeminfo.exe | sls Version
    winver
- ps: docker pull mcr.microsoft.com/powershell:lts-7.2-nanoserver-1809
- ps: docker images
- ps: |
    docker run -it mcr.microsoft.com/powershell:lts-7.2-nanoserver-1809 pwsh -Command '[System.Environment]::OSVersion.Version'
