image:
- Visual Studio 2022
- Visual Studio 2019
build: "off"
init:
- ps: |
    &$Env:ProgramFiles\Docker\Docker\DockerCli.exe -SwitchDaemon
- ps: |
    &$Env:ProgramFiles\Docker\Docker\DockerCli.exe -SwitchWindowsEngine
install:
- ps: |
    [System.Environment]::OSVersion
    systeminfo.exe | sls Version
    winver
- ps: docker images
- ps: |
    docker build --tag taylorm/paperdraw:appveyor .
