image:
- Visual Studio 2022
- Visual Studio 2019
build: "off"
init:
- ps: |
    &$Env:ProgramFiles\Docker\Docker\DockerCli.exe -SwitchDaemon
- ps: |
    &$Env:ProgramFiles\Docker\Docker\DockerCli.exe -SwitchWindowsEngine
install:
- ps: |
    [System.Environment]::OSVersion.Version
    systeminfo.exe | sls Version
    winver
- ps: docker images
- ps: |
    docker run -it mcr.microsoft.com/windows/servercore:1803 powershell -Command '[System.Environment]::OSVersion.Version'
- ps: |
    docker build -t mytest:latest .
