"on":
- push
jobs:
  buildx:
    runs-on: windows-2019
    steps:
    - name: Get size of windows image
      uses: Amadevus/pwsh-script@v2
      id: get-size-of-windows-image
      with:
        script: |
          docker images
    - run: echo "${{ steps.get-size-of-windows-image.outputs.result }}"
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        use: true
    - name: Login to dockerhub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build
      run: |
        docker build . -f Dockerfile -t docker.io/${{ secrets.DOCKERHUB_USERNAME }}/paperdraw:latest
        docker build . -f Dockerfile -t docker.io/${{ secrets.DOCKERHUB_USERNAME }}/paperdraw:latest1
        docker build . -f Dockerfile -t docker.io/${{ secrets.DOCKERHUB_USERNAME }}/paperdraw:latest2
    - name: Push
      run: |
        docker image push docker.io/${{ secrets.DOCKERHUB_USERNAME }}/paperdraw:latest
        docker image push docker.io/${{ secrets.DOCKERHUB_USERNAME }}/paperdraw:latest1
        docker image push docker.io/${{ secrets.DOCKERHUB_USERNAME }}/paperdraw:latest2
